### ISSUE TITLE
Gramatical fixes with Immutability and Loops

### ISSUE THREAD

**Issue by lifehug** [codingrehab/podcasts#11]
1. The conj operation does not modify the collection but return a copy of it instead

- The conj operation does not modify the collection but return_s_ a copy of it instead

- The conj operation does not modify the collection but will return a copy instead

2. But what does it mean to be immutable? It means the all the code you write or use can not modify an instance of an object or data structure but create a new one that reflects the change you expected.

- But what does it mean to be immutable? It means the all the code you write or use can not modify an instance of an object or data structure but _will_ create a new one that reflects the change you expected.

- But what does it mean to be immutable? It means the all the code you write or use can not modify an instance of an object or data structure, _rather it will_ create a new one that reflects the change you expected.

3. Though we will not use a classic while loop we can do something very similar by using recursion.

- Though we will not use a classic while loop_,_ we can do something very similar ~using recursion.

4. Many of these concepts are indeed so common that specific functions are included in each language to achieve the same functionality.

- Many of these concepts are indeed so common that specific functions are included in each language_,_ to achieve the same functionality.

5. Though there is a combination of functions each element is only traversed once and on demand due to the lazy nature of sequences in Clojure.

- Though there is a combination of functions, each element is only traversed once...  and on demand due to the lazy nature of sequences in Clojure.

6. I can not emphasize enough how important is to learn as much as we can which common concepts are already implemented and how to use those functions in our code.

I can not emphasize enough how important is to learn _-_ as much as we can _-_ which common concepts are already implemented, and how to use those functions in our code.

7. Mapping to a collection and concatenate the result after is a very common scenario. So common that there is a function that composes both.

- Mapping to a collection _and then concatenating the result is_ a very common scenario. So common that there is a function that composes both.

8. In Haskell the function is called zip and takes two collections and returns a collection of tuples with one element of each collection.

- In Haskell the function is called _zip, which takes two collections and returns a single collection of tuples. Each tuple contains an element of both collections._

9. The map function expects a function that the arity matches the collections passed as parameter. For two collections it should be a function that receives two parameters, for three collections a function that receives three parameters and son on.

- The map function expects a function _whose_ arity matches the collections passed as parameter. GIven two collections it should be a function that receives two parameters; Three collections a function that receives three parameters... and son on.

10. Reducing a collection means to transform all the elements not only one element at a time but also including an accumulator that can help us decide what to do.

- Reducing a collection, means to transform all the elements into a value. This transformation does not purely happen one element at a time, but in conjunction with an accumulator -  which can help us decide what to do.

11. The reduce function takes first a function with two parameters (the accumulator and the current element), then an initial value and last the collection which to take the elements from.

- The reduce function will expect a function with two parameters (the accumulator and the current element), then an initial value and finally the collection from which to take the elements.

12. frequencies is a reduction that checks the frequency of each element and returns a hashmap with the element as key and the count as value.

- frequencies is a reduction that checks the frequency of each element, and returns a hashmap. The hash map contain the element as a key and the count as a value.

13. partition takes a number and a collection and returns that amount of elements at a time.

- partition takes a nu_mber, a collection and returns a new collection, partitioned by the given amount of elements_ .

14. Because is an infinite sequence we are taking the first twenty memebers of the sequence.

- Because _this produces an_ infinite sequence we are taking the first twenty memebers of the sequence.

15. Writing custom loops is a lot of effort and more often than not there is an alternative already written that can help you out. Sometimes needs to be combined with other functions and sometimes requires small helper functions.

Though list comprehensions and many of the functions we just reviewed are very common in functional languages they also exists in many others.

Do not get discouraged, search for them, you may be surprised of what you will find.

- 
_Writing custom loops is a lot of effort, and more often than not, there is an alternative already written to help you out. Functions often need to be combined with other functions and frequently require small helper functions.

Though the list comprehensions, and many of the functions we just reviewed are very common in functional languages, they also exists in many others languages._

Do not get discouraged, search for them, you may be surprised of what you will find.

**Comment by lifehug** [comment]
These are all debatable, and I'd actually like to reference some of my literature to verify. It's also very debatable to what extent we care. I think a natural voice is often easier to learn from, compared to a rigid but correct form.

**Comment by amirci** [comment]
I think they are good!

Do you want me to just change them or you are going to do a MR ?
